import json
from typing import List, Dict, Optional

# --- 1. Long-Term Memory Schema ---

class RecipientProfile:
    """
    Defines the structure of data stored in the Long-Term Memory (Memory Bank).
    This stores persistent, non-budget-related preferences for personalization.
    """
    def __init__(self, recipient_name: str,
                 persistent_interests: List[str],
                 past_successful_gifts: List[str],
                 disliked_categories: List[str]):
        """
        Initializes the recipient's persistent profile.
        """
        self.recipient_name = recipient_name
        self.persistent_interests = persistent_interests
        self.past_successful_gifts = past_successful_gifts
        self.disliked_categories = disliked_categories

    def to_dict(self) -> Dict:
        """Converts the profile object to a dictionary for storage."""
        return self.__dict__

    @staticmethod
    def from_dict(data: Dict) -> 'RecipientProfile':
        """Creates a Profile object from stored data."""
        return RecipientProfile(
            recipient_name=data.get('recipient_name', ''),
            persistent_interests=data.get('persistent_interests', []),
            past_successful_gifts=data.get('past_successful_gifts', []),
            disliked_categories=data.get('disliked_categories', [])
        )

# --- 2. Inter-Agent Data Schema ---

class GiftIdea:
    """
    Defines the structured output generated by the Gift Researcher Agent
    and passed to the Aggregator Agent for final delivery and custom tool checking.
    """
    def __init__(self,
                 recipient: str,
                 gift_title: str,
                 description: str,
                 estimated_price: float,
                 product_link: str,
                 currency: str = "USD", 
                 budget_check_status: str = "Pending"):
        """
        Initializes a potential gift idea.
        """
        self.recipient = recipient
        self.gift_title = gift_title
        self.description = description
        self.estimated_price = estimated_price
        self.product_link = product_link
        self.currency = currency 
        self.budget_check_status = budget_check_status

    def to_json_string(self) -> str:
        """Converts the gift idea object into a JSON string for inter-agent communication."""
        return json.dumps(self.__dict__)

    @staticmethod
    def from_json_string(json_str: str) -> 'GiftIdea':
        """Creates a GiftIdea object from a JSON string."""
        return GiftIdea(**json.loads(json_str))