# https://taskfile.dev

version: '3'

dotenv: ['.env']

tasks:
  build:
    cmds:
      - docker build -t holiday-gift-savoir .

  run:
    deps: [build]
    cmds:
      - docker run -p 3011:3011 -e GEMINI_API_KEY=$GEMINI_API_KEY holiday-gift-savoir

  dev:
    deps: [build]
    cmds:
      - docker run -it -p 3011:3011 -e GEMINI_API_KEY=$GEMINI_API_KEY -v .:/app holiday-gift-savoir bash
